### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by rickgorman** [rickgorman/agile-manager#2]

**Comment by rickgorman** [comment]
Hi Ali. I believe this is done. Give it a look over when you can, please.

**Comment by rickgorman** [comment]
Added demo login button to / route.

**Comment by AM-Harris** [comment]
Looking really good! A few things: 

- [ ] Email authentication is a bonus feature, and as such, isn't currently implemented. That's fine, but it also means you don't actually have authentication because your are auto-assigning the password as password. I can't then mark auth done until a user can enter a password, and access to certain features is based on authentication using that password. I would say until you are ready to implement email auth, you'll want a temporary password input field on sign up.
- [ ] Remove log out from the header when a user isn't logged in.

**Comment by rickgorman** [comment]
- Added logic to conditionally render login/logout depending on isLoggedIn prop.
- Changed logout action to first dispatch receiveCurrentUser(null) and THEN logout on the backend.

**Comment by rickgorman** [comment]
I believe this is ready to be marked done.

- Rolled back the change with logout behavior. Now, the history.push happens AFTER the logout promise finishes.
- Added password field to signup page (With error handling)
- Login/logout links work smoothly

**Comment by rickgorman** [comment]
standby. pushing to heroku.

**Comment by rickgorman** [comment]
...and it's now pushed to heroku. Awaiting your review.

**Comment by AM-Harris** [comment]
LOOKS GOOD TO ME! I'll mark done, but please remember you'll need to style and apply a picture to your landing page

**Comment by rickgorman** [comment]
Done. Thanks Ali.
